---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: notes-scala
spec:
  encryptedData:
    .dockerconfigjson: AgAaCOY9dyWUWa7zYF/U/H/PBmChYqVjKRUDlR2w0DUzEfmb9KcQerCh9rioCF8RJYZdLsYOe4xpZSzoPGTiMifmyz35KlBz3RokaYwoy3TTvp6NL4OZ90JXzmf3uyxPsY0f+WAOBILtvZUd/UHnwkD+xb+yG1udgKX53X/vvVMZ86yCHIF/WU5r1WsC0YyvWr7vbKI77sKveyoqxbvP0GJvClojK65AzEhBXyl0HD0ckKC5qDuISKSBC80zBHNbUx5tSuevjRRi/MyIcPx7ylLj8Yb2m2iYX0CZRJu7/27VlTUl/yfbI2SiFkxRUwpUKBRXVejPWE/NpKoL+QYVaz/8gIX1Pi+YufpdO6i0FsGl1ugxqPm/cnIzKHIZyoAtbDuXZwO8mykBLYiNy5qbETeSXkv1hugzO7eN9nk0Kkx9CYwhmiBz++5cARk6enBUnZNFTD8V8N3XUcLcoe3pVYqijkHGJnM7nLqnaGCW3f6l/jbNP5Cedhmy+/vSqajD5L5jSkfu/JYeU5hrgq3c52nBo02v9qTMLrouD/BfkEExpEgmnSfHoL3V4KiVryws4FiwAzVLnxGR879K6rkhQ0P0zHriszhC1m9CmFDtncC6mGU1dqVi4+5b4Vzb1lHAvXCXVsrE3bXqJfwYp09QZKl/SwSiToYOGkM1qlGpCnA5Hrd86rdOjV/cmWQ28EE9raing6/ptj/kecuPiIqmU3w/zybAe+I53j+AfCOlC1GdeaFk61KzJFegIzF8HmNKAG2LatQWy1G/4lEHLjf3Dm1/+N54I4R56Yj2pS7jWtHU5qbOhSdHx1EXPMFKnITIWRaT1lXdkV3hig6+orZwDatCSGWjIpfE3reFCl+AnxNLuccgWghObc0mIAXHMuRJ8/t00ulQl8DW6ykUgftohQOnlxul2IasrTs9uuQ=
  template:
    metadata:
      name: ghcr-secret
      namespace: notes-scala
    type: kubernetes.io/dockerconfigjson
