---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-secret
  namespace: notes-scala
spec:
  encryptedData:
    .dockerconfigjson: AgA5RRJo6rQf1jWq6wCJuHv5xQ6E+P11BsLzwK0RL6y5uvNgHDRLYEvALLFMf70LGRzXMlCsDUy9hvkyONVFh0Fi9wc+nfHw4QhYpO85F8awrQRBQH+5yGeH5sbThQNVOlUGQNxbHPClcB0Qsb2FxBAvH9sU1mGUXjSli+CykJ+Aq1IG3m9rZNAg+PVEAECM/ZvotXL23XyPdhx9hzvwax6Iu0JJawSC2JXbmAVFinQvFlDabyg5FrAgiscQqcoeIVpb2C9VeUWWXGdeEWdbgGT++TxUZ9Ni/8GUEucEzUDcEQIpHTW8LEs0beqJK4hUt4oCB7zw7fJbB5bs2zLnJvWiPIUNU8X1Tshoga7ZcrmV5nrHh0z3jyfhOZMFUn1EQgBg0LIROpa+gcIE3wiPh+PSPXpF805yPhz+fyeniXpcb40zsHVEdRJ874fQUQQAGYDRNH7XYkEyepMZoeY8S23JtzuxGFQRHvTJhk5+dX7E4GDtsOcX+8C+deZHiyucVijc/qFBTxMTeowzbD+xuzuNd1I1JWzmA4wmizPyTctrDLeVpSmro6pPgmxcuYlWhacoqTH1EyzuLuelFZTAQv6j0tg8Bh0krHqJzBnzCZ+axfiNsPzozp24oOZASZZrv6BnRD2YNZMbJR1k1M4i53vmAE630H84wh7+h17BbzBoluPs6Pgz+TgwRydlg+LFdakcQvWv07TUpgYKHUM5+VMyeP6Gkje9oOkJvLFlcGk0DqyUKfE5EQYipofWNOjMLrudYqPBEASlOPK+k7FPN5xTAMkQ7Hc4N4a87U/7Y8VFCGtCeJgxNBrHsuKns8Cgop3Ghb//NxcH7hAfO27Y5cP/ASJqPuPN9i5lWb537BLA3HL2XJYNYTVnPUMCzdhYNWgpqUNSoCtRKo5OEZK9pzAx8+Ax8U8jH9+Gfjo=
  template:
    metadata:
      name: ghcr-secret
      namespace: notes-scala
    type: kubernetes.io/dockerconfigjson
